n_of_particles: #パーティクル数
 100
update: #背景を更新する頻度,何回ごとにUpdateするか 0ならUpdateしない
 #100
 0
max_lrf_range: #LRFの最大計測範囲
 10.0
min_lrf_range:
 0.1
target_area: #ターゲットの存在範囲
 # Huis Ten Bosch
 #[ 0.0, 0.0, 20.0, 40.0 ]
 # 928
 [ -3.0, -1.25, 3.0, 1.25 ]
particle_area: #クラスタを中心にパーティクルを散布する範囲(0.1m 四方)
 0.1
m_sigma: #尤度計算用の分散
 0.3
pos_noise: #パーティクル更新時のノイズ(位置)
 0.01
vel_noise: #パーティクル更新時のノイズ(速度)
 0.01
max_vel:
 0.1
m_min_distance: #クラスタと既存のPFとの距離が1m以下なら,既存のPFに紐付け
 0.5
m_initial_dist: #500mm四方にパーティクルを初期配置
 0.3
lrf1_pos: #LRF1の座標(x, y, yaw[deg])
 # 928
 #[ 0.0, 0.0, 0.0 ]
 # bsen-p
 #[ 3.0, -1.1, 93.0 ]
 [ -3.0, -1.25, 90.0 ]

lrf2_pos: #LRF2の座標(x, y, yaw[deg])
 # Huis Ten Bosch
 #[ 1.0, 18.5, 270.0 ]
 # 928
 #[ 4.5, 2.0, 180.0 ]
 # bsen-p
 #[ 2.8, 1.4, 273.0 ]
 
#[ -3.0,  2.5, 270.0 ]

[ 3.0, -1.23, 88.8 ]

lrf3_pos: #LRF3の座標(x, y, yaw[deg])
 # Huis Ten Bosch
 #[ 22.35, 14.7, 270.0 ]
 # 928
 #[ 4.1, 9.55, 180.0 ]
 # bsen-p
 #[ -3.3, 1.0, 273.0 ]
 [  3.0, 1.25, 269.0 ]

lrf4_pos: #LRF4の座標(x, y, yaw[deg])
 # 928
 #[ 1.85, 9.55, 0.0 ]
 # bsen-p
 #[ -3.0, -1.6, 95.0 ]

 [ -3.0, 1.25, -89.0 ]

lrf_active: # LRFを使用するかどうか
 # Huis Ten Bosch
 #[ true, true, true, false ]
 # 928
 [ true, true, true, true ]
